chore(docs): update naming to match new branding initiative
commercetools/commercetools-sdk-php-v2 pull request #83
Opened 2022-06-13 07:22 UTC by jherey

# Description
This PR follows the rebranding initiative by the Marketing and Docs team to change commercetools to Composable Commerce.

https://github.com/commercetools/clients-team-internal/issues/87

NB: This PR does not update the tests, as this is out of scope.

2022-06-13 07:55 UTC, barbara79 approved these changes
LGTM 👍

2022-06-13 08:59 UTC, melindafekete requested changes

2022-06-13 08:59 UTC, melindafekete commented on composer.json
> +  "description": "The official PHP SDK of commercetools Composable Commerce APIs",
```suggestion
  "description": "The official PHP SDK of commercetools Composable Commerce APIs",
```
```suggestion
  "description": "The official PHP SDK for the commercetools Composable Commerce APIs",
```

2022-06-13 08:59 UTC, melindafekete commented on lib/commercetools-api/docs/RequestBuilder.md
> +The cart must have a shipping address set before creating an order. When using Composable Commerce TaxMode,
```suggestion
The cart must have a shipping address set before creating an order. When using the Platform TaxMode,
```

2022-06-13 08:59 UTC, melindafekete commented on lib/commercetools-api/docs/RequestBuilder.md
> +When using Composable Commerce TaxMode, the shipping address is used for tax calculation.
```suggestion
When using Platforme TaxMode, the shipping address is used for tax calculation.
```

2022-06-13 08:59 UTC, melindafekete commented on lib/commercetools-api/src/Models/Cart/Cart.php
> +     * Will be set automatically in <code>Composable Commerce</code> TaxMode.
```suggestion
     * Will be set automatically in the <code>Platform</code> TaxMode.
```

2022-06-13 08:59 UTC, melindafekete commented on lib/commercetools-api/src/Models/Cart/CartBuilder.php
> +     * Will be set automatically in <code>Composable Commerce</code> TaxMode.
```suggestion
     * Will be set automatically in the <code>Platform</code> TaxMode.
```

2022-06-13 08:59 UTC, melindafekete commented on lib/commercetools-api/src/Models/Cart/CartModel.php
> +     * Will be set automatically in <code>Composable Commerce</code> TaxMode.
```suggestion
     * Will be set automatically in the <code>Platform</code> TaxMode.
```

2022-06-13 08:59 UTC, melindafekete commented on lib/commercetools-api/src/Models/Cart/CustomLineItem.php
> +     * <p>Will be set automatically in <code>Composable Commerce</code> TaxMode once the shipping address is set is set.
```suggestion
     * <p>Will be set automatically in the <code>Platform</code> TaxMode, once the shipping address is set is set.
```

2022-06-13 08:59 UTC, melindafekete commented on lib/commercetools-api/src/Models/Cart/CustomLineItemBuilder.php
> +     * <p>Will be set automatically in <code>Composable Commerce</code> TaxMode once the shipping address is set is set.
```suggestion
     * <p>Will be set automatically in the <code>Platform</code> TaxMode, once the shipping address is set is set.
```

2022-06-13 08:59 UTC, melindafekete commented on lib/commercetools-api/src/Models/Cart/CustomLineItemModel.php
> +     * <p>Will be set automatically in <code>Composable Commerce</code> TaxMode once the shipping address is set is set.
```suggestion
     * <p>Will be set automatically in the <code>Platform</code> TaxMode, once the shipping address is set is set.
```

2022-06-13 08:59 UTC, melindafekete commented on lib/commercetools-api/src/Models/Cart/LineItem.php
> +     * <p>Will be set automatically in <code>Composable Commerce</code> TaxMode once the shipping address is set is set.
```suggestion
     * <p>Will be set automatically in the <code>Platform</code> TaxMode, once the shipping address is set is set.
```

2022-06-13 08:59 UTC, melindafekete commented on lib/commercetools-api/src/Models/Cart/LineItemBuilder.php
> +     * <p>Will be set automatically in <code>Composable Commerce</code> TaxMode once the shipping address is set is set.
```suggestion
     * <p>Will be set automatically in the <code>Platform</code> TaxMode, once the shipping address is set is set.
```

2022-06-13 08:59 UTC, melindafekete commented on lib/commercetools-api/src/Models/Cart/LineItemModel.php
> +     * <p>Will be set automatically in <code>Composable Commerce</code> TaxMode once the shipping address is set is set.
```suggestion
     * <p>Will be set automatically in the <code>Platform</code> TaxMode, once the shipping address is set is set.
```

2022-06-13 08:59 UTC, melindafekete commented on lib/commercetools-api/src/Models/Cart/ShippingInfo.php
> +     * <p>Will be set automatically in <code>Composable Commerce</code> TaxMode once the shipping address is set is set.
```suggestion
     * <p>Will be set automatically in the <code>Platform</code> TaxMode, once the shipping address is set is set.
```

2022-06-13 08:59 UTC, melindafekete commented on lib/commercetools-api/src/Models/Cart/ShippingInfoBuilder.php
> +     * <p>Will be set automatically in <code>Composable Commerce</code> TaxMode once the shipping address is set is set.
```suggestion
     * <p>Will be set automatically in the <code>Platform</code> TaxMode, once the shipping address is set is set.
```

2022-06-13 08:59 UTC, melindafekete commented on lib/commercetools-api/src/Models/Cart/ShippingInfoModel.php
> +     * <p>Will be set automatically in <code>Composable Commerce</code> TaxMode once the shipping address is set is set.
```suggestion
     * <p>Will be set automatically in the <code>Platform</code> TaxMode, once the shipping address is set is set.
```

2022-06-13 09:00 UTC, melindafekete commented on composer.json
> +  "description": "The official PHP SDK of commercetools Composable Commerce APIs",
```suggestion
  "description": "The official PHP SDK for the commercetools Composable Commerce APIs",
```

2022-06-13 09:04 UTC, melindafekete commented
@barbara79 @jherey do you understand why we can't rename Platform in 'Platform Taxmode', or shall I explain in further detail? Not sure if there's any more SDKs to do, but please keep an eye out for this one

2022-06-13 09:11 UTC, jenschude commented
> @barbara79 @jherey do you understand why we can't rename Platform in 'Platform Taxmode', or shall I explain in further detail? Not sure if there's any more SDKs to do, but please keep an eye out for this one

I also think that the comment is not complete here. It's not talking about the platform itself but about the platform enum value.

2022-06-13 14:19 UTC, jherey commented
> @barbara79 @jherey do you understand why we can't rename Platform in 'Platform Taxmode', or shall I explain in further detail? Not sure if there's any more SDKs to do, but please keep an eye out for this one

Oh yeah I do understand. It's mostly a group update using the code editor, I'll take time to check these updates going forward.

2022-06-14 07:22 UTC, melindafekete commented on lib/commercetools-api/docs/RequestBuilder.md
> +When using Platforme TaxMode, the shipping address is used for tax calculation.
```suggestion
When using Platform TaxMode, the shipping address is used for tax calculation.
```

2022-06-20 15:29 UTC, melindafekete approved these changes

2022-06-21 07:01 UTC, merged